from .triage_prompt import PMCATRIAGE_SYSTEM_MESSAGE
from .triage_reviewer_prompt import PMCATRIAGE_REVIEWER_SYSTEM_MESSAGE
from .triage_structured_prompt import PMCATRIAGE_STRUCTURED_SYSTEM_MESSAGE


__all__ = [
    "PMCATRIAGE_SYSTEM_MESSAGE",
    "PMCATRIAGE_REVIEWER_SYSTEM_MESSAGE",
    "PMCATRIAGE_STRUCTURED_SYSTEM_MESSAGE",
]
