services:
  assistant-emitter:
    build:
      context: .
      dockerfile: Dockerfile
    image: PMCA/assistant-emitter:latest
    container_name: assistant-emitter
    ports:
      - "11000:8000"
    restart: unless-stopped
